name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
    tags-ignore:
      - '*' # ignore all tags, our 'release' action triggers on tags


jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: test
        run: make test
