name: CI
on: [push, pull_request]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build
      - name: test
        run: make test
