name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: extract tag for release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: build all image variants
        run: make build VERSION=$RELEASE_VERSION
      - name: test all image variants
        run: make test VERSION=$RELEASE_VERSION
      - name: setup qemu (to run builders other than host)
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: setup buildx (used by our 'release' makefile target for multi-arch releases)
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: release all image variants to docker hub
        run: make release VERSION=$RELEASE_VERSION
